### ISSUE TITLE
Migrate to tox-dev and v4 support

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox-ansible#100]
Hello, would you consider moving the project under the tox-dev umbrella? See documentation under https://tox.readthedocs.io/en/rewrite/plugins.html#adoption-of-a-plugin-under-tox-dev-github-organization 

Furthermore, tox v4 is getting ready and we'd like to make sure this plugin is supported from day 1, we're collecting feature gaps for this under https://github.com/tox-dev/tox/issues/1974. Would be great if you could join our development chat under https://discord.gg/tox so we can assist with this. If you do so please drop in a line in the `#plugin` chat with the name of the repository you maintain. Thanks!

**Comment by ssbarnea** [comment]
I do support the change and I do thing that having all plugins under the same organization will benefit everyone.

**Comment by greg-hellings** [comment]
I'm in support of this move, as well. I have been following the tox rewrite branch occasionally and would love to have tox4 support at release time in this plugin.

**Comment by ssbarnea** [comment]
Done!
