### ISSUE TITLE
Auto-add missing variables to passenv

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox-ansible#106]
One very common mistake while using molecule with tox is to forget to alter passenv to add at least:
```
passenv =
  DOCKER_*
  CONTAINERS_*
  HOME
  SSH_AUTH_SOCK
```

Missing any of these can cause various failures which are no easy to debug by the average user. Adding them by default may make the plugin easier to use.

**Comment by greg-hellings** [comment]
Currently we /should/ be passing through
```python
passenv_list = (
    "HOME",
    "DOCKER_HOST",
    "CONTAINER_HOST",
)
```

Are these currently passing through? If not, then we need to write a test for that and fix it. If so, then we simply need to expand it. My use cases seem to indicate they are passing through properly, but I don't use any of those three things very heavily in my testing.

**Comment by ssbarnea** [comment]
For sure `SSH_AUTH_SOCK` is needed, or you will be surprised to see failure from podman/docker on removes. That was my case, but i remembered about the other ones.
