### ISSUE TITLE
[ansible-test]: Support for more flexible docker setups (using --target/--controller)

### ISSUE THREAD

**Issue by maxhoesel** [tox-dev/tox-ansible#130]
I'm running into an issue with how `tox-ansible` handles `ansible-test` targets that are executed in docker containers. By default, `ansible-test` simply adds the `--docker default` [flags to the `ansible-test` call when Docker is detected on the host](https://github.com/tox-dev/tox-ansible/blob/55b129c53496db34ead29de91060b65437e3d551/src/tox_ansible/ansible/__init__.py#L134). This flags controls the docker image used for both the controller and target host in module tests.

While this works fine in most scenarios, recent `ansible-test` versions (2.12 and up) added new flags (`--controller` and `--target`) that allow the user to specify a custom environment for both the controller and the target node separately (see [here](https://github.com/ansible/ansible/pull/75605)). This is a very useful feature if the requirements for the controller and the target node are different. These `--controller` and `--target` options are **mutually exclusive** with the old `--docker` option, so it's not possible to pass them into the `ansible-test` call from `tox`.

I'm currently in a situation where I need to use these new arguments, but can't because they conflict with the default `--docker` arg added by `tox-ansible`. Specifically, I have a [collection](https://github.com/maxhoesel/ansible-collection-caddy) that still supports Python 2.7 and requires the `requests` library, but said library is no longer available as a package on the `default` container now that `ansible-test` 2.13 switched that image from [Ubuntu 18.04 to 20.04](https://github.com/ansible/ansible/blob/stable-2.13/changelogs/CHANGELOG-v2.13.rst). This is a problem, because while I can overwrite the `default` container with another one (via posargs) where that library still exists (such as `centos7`), these containers are then too old to run the Ansible controller (which now requires py38).

The new `--target` and `--controller` flags solve this issue by allowing users to specify a controller container (such as the default one) as well as an older target container like so:

`ansible-test integration --requirements --controller docker:default --target docker:centos7``

I would like to see support for these options added to tox-ansible. Perhaps the automatic addition of the `--docker`/`--venv` flag could be toggled off with an option so that users could pass in these args?

**Comment by maxhoesel** [comment]
Thanks for the quick reply! From what I can tell by looking at the source, `tox-ansible` only seems to add the `--requirements` arg (which is almost always required AFAIK) and the args that configure the [testing environment](https://github.com/tox-dev/tox-ansible/blob/55b129c53496db34ead29de91060b65437e3d551/src/tox_ansible/ansible/__init__.py#L133) (`--docker` or `--venv`). As long as there is a way to disable those arguments everything should work just fine.

I think that having an `ansible_test_args` option that overrides these builtins would work too, but it could become unwieldy if one wants to call a tox scenario like `integration` multiple times with different controllers/targets. I think I'd prefer a option that just toggles this behavior on/off, so that users can add their own arguments.

Perhaps we could add an `ansible_test_platform` option that could be one of these values:
- `auto` (default): Automatically detect whether to use a venv or docker (the current behavior)
- `venv`: Add the ´--venv` arg
- `docker`: Add the `--docker default` args
- `manual`: Don't add anything, the user needs to se the args via posargs

This way, users could explicitly select their environment or just disable the feature if they don't need it/have more specific needs.

**Comment by greg-hellings** [comment]
Hmm, I like it. Maybe it would be more clear to use the value "posargs" in
place of "manual" so it is more clear where the user can specify the manual
options?

**Comment by ssbarnea** [comment]
My team (Ansible devtools) is planning to do some serious work in that area in the following months so if would make sense to delay implementing major changes in that area.

Probably implementing a way to pass arbitrary commands down would be the most flexible approach.

**Comment by maxhoesel** [comment]
That's good to know! That said, isn't the support for arbitrary commands already kind of there (using the user-supplied posargs)? That approach has worked well for me so far. Adding an option like `ansible_test_platform` would just always allow the user to input their arbitrary commands, without tox-ansible conflicting, even if things change upstream.

@greg-hellings That makes sense to me, yeah.

**Comment by maxhoesel** [comment]
I've created an initial implementation [here](https://github.com/maxhoesel/tox-ansible/pull/1). So far it seems to work for me, but I'll have to do some more testing to be sure. I'll also wait for your reply regarding the upcoming changes that @ssbarnea mentioned before I'll open a PR.

**Comment by greg-hellings** [comment]
With @ssbarnea's comment I was going to just leave it with two options, but you have already implemented all the ones we spoke about. The only tweak I would make to the implementation you have there is to make an assertion that the configuration is valid after it is read from the config file. Otherwise it looks like a nice, clean implementation!

**Comment by maxhoesel** [comment]
Thanks for the feedback! I have opened a initial PR here: #131

**Comment by greg-hellings** [comment]
This is now included in the 1.8.0 release. Thanks for the PR!
