### ISSUE TITLE
Replace rsync command

### ISSUE THREAD

**Issue by hille721** [tox-dev/tox-ansible#192]
HI @cidrblock,

thanks for the great rework of this tox plugin. We spoke on the Ansible community contributor summit in Boston and I really like the idea.
I now had time to migrate my tox setup to use ansible-tox, what was nice as I was able to remove ~100 lines of tox config. Locally it is already working fine, but I have a problem now on my Gitlab CI with the rsync command:
I'm just using the normal Python container images, and in there `rsync` is not available. I've also tried the "ansible-core-test-container" image, but also there `rsync` is missing.

Now the question: can't the `rsync` command easily replaced with `cp` or even better nativ Python functions? Or we could also use `ansible-galaxy` to build the collection and install it inside the tox environment (this my approach so far).

**Comment by hille721** [comment]
As git is a requirement anyhow, we could use `git ls-files` to get only files which are not excluded by `.gitignore` and then doing the copy with `cp`:

``` python
f"cp -r --parents $(git ls-files 2> /dev/null || ls) {galaxy_build_dir}"
```

**Comment by hille721** [comment]
https://github.com/tox-dev/tox-ansible/commit/e304ce34613f568c08435c88f73b03a13c4f25b0

This works for me. 
Let me know what do you think or do you have better ideas?

**Comment by cidrblock** [comment]
I hadn't considered `rsync` not being available :)  although I haven't tested it, the `git` variation seems like a viable approach.  If you'd like to do a PR with that we can get it in and do a release and see how it goes.
