### ISSUE TITLE
Added environments are included in envlist automatically

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox-ansible#40]
I was bit surprised by the fact that running "tox" did also include the environment created by tox-ansible instead of the list that I manually defined using  `envlist`.

This can prove to be problematic, for some users and also cause accidents.

@greg-hellings IMHO, the generated environments should not be added to the default list. What do you think?

**Comment by greg-hellings** [comment]
So I couldn't find a good way to get them listed with a `tox -l` unless I added them to envlist. I thought there was a check in place to only add them when the envlist is empty, but that check - or my memory - might be incorrect.

**Comment by ssbarnea** [comment]
Well, the correct way to list all env was `tox -a[v]` not `tox -l[v]`. My expectation is that that `-l` should stick to what user manually declared.

What I am not sure is what happens when user did not mention anything in envlist, probably it should default to `-a`.

**Comment by greg-hellings** [comment]
One option might be to change this logic here: https://github.com/ansible-community/tox-ansible/blob/master/src/tox_ansible/hooks.py#L73

If we add an additional command line option, we can make this appending optional. The question is, should we default to on or off?

**Comment by greg-hellings** [comment]
So one of the difficulties of expecting the user to add to the list manually is that the point of the plugin was to reduce the need to manually define the list of environments. If we don't add them, it makes discovering the list difficult and makes users, once again, need to manually curate the list of scenarios.

Currently, my usage pattern goes

* collect `tox -l --ansible-driver docker --ansible-driver podman` to get the list of all Docker and Podman environments
* convert list to a JSON array
* feed JSON array into next step in GitHub Actions pipeline

For execution elsewhere I do the same but with `tox -l --ansible-driver openstack` and feed that into a massively parallel Jenkins execution.

I'm not committed to keeping the first step exactly the same, but the functionality needs to remain. Messing with the output of `tox -l` was the main way I could figure out to do that. But I'm not against updating the hooks themselves to specify the output directly. Even asking for a JSON array so I'm not using bash hooks for that, like I'm currently doing.

**Comment by greg-hellings** [comment]
I think my proposal in the other issue of adding an INI enable flag could also resolve this. Then it would detect and append when it's enabled rather than just every time tox is run somewhere that happens to have a path matching `molecule/*/molecule.yml` glob. If it's not enabled, then it wouldn't do anything.

I do not think we need a half-way state where the envs are generated but not added to the default list. I think enabling the plugin as opt-in is sufficient. What do you think?
