### ISSUE TITLE
tox-ansible should do nothing on repos unrelated to ansible

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox-ansible#76]
If you install tox-ansible plugin at system or user level, it will alter the list of tox environments for any repository, even if it has nothing to do with ansible,  adding at least `lint_all` and sometimes I even found add a molecule scenario I had inside examples/ folder, which was never intended to be executed.

What makes the issue more painful is that it also adds these to the default environment list, so just running `tox` will also trigger these too.

If we want to make the plugin more popular we should be more careful about what it does on random repositories, or we will succeed in scaring some users.

**Comment by greg-hellings** [comment]
Detecting the present of a "galaxy.yml" file in the same path as {toxinidir} would be a start for that. It would at least give us the ability to avoid running in a place where we aren't in an Ansible collection. However, we currently have tests specifically testing that we *do* run where there isn't a collection. To wit: `tests/fixtures/not_collection`.

Maybe we should search for an opt-in tox.ini flag? Something like

```ini
[ansible]
enabled = true
```

?

**Comment by greg-hellings** [comment]
We currently have the check in `src/tox_ansible/ansible/__init__.py` line 59-65 to check that either there are scenarios discovered or that a `galaxy.yml` exists in the running directory. Is that sufficient to close this out, or is there other effort we need to do to detect this?
