### ISSUE TITLE
tox-ansible fails on triopleo-quickstart repo

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox-ansible#78]
Using tox-ansible on https://github.com/openstack/tripleo-quickstart repo produces a weird error from tox side:
```
$ tox -e install-deps
install-deps create: /Users/ssbarnea/c/opendev/tripleo-quickstart/.tox/ansible
install-deps installdeps: -r/Users/ssbarnea/c/opendev/tripleo-quickstart/test-requirements.txt, molecule, ansible-lint, yamllint, flake8, pytest, testinfra, ansible, molecule-containers, molecule-docker, molecule-podman, molecule-openstack, openstacksdk, os-client-config, molecule-ec2, boto, boto3, molecule-vagrant
ERROR: invocation failed (exit code 2), logfile: /Users/ssbarnea/c/opendev/tripleo-quickstart/.tox/install-deps/log/install-deps-3.log
================================================================ log start ================================================================

================================================================= log end =================================================================
ERROR: could not install deps [-r/Users/ssbarnea/c/opendev/tripleo-quickstart/test-requirements.txt, molecule, ansible-lint, yamllint, flake8, pytest, testinfra, ansible, molecule-containers, molecule-docker, molecule-podman, molecule-openstack, openstacksdk, os-client-config, molecule-ec2, boto, boto3, molecule-vagrant]; v = InvocationError('/Users/ssbarnea/c/opendev/tripleo-quickstart/.tox/install-deps/bin/python -m pip install -chttps://releases.openstack.org/constraints/upper/master -r/Users/ssbarnea/c/opendev/tripleo-quickstart/test-requirements.txt molecule ansible-lint yamllint flake8 pytest testinfra ansible molecule-containers molecule-docker molecule-podman molecule-openstack openstacksdk os-client-config molecule-ec2 boto boto3 molecule-vagrant', 2)
```

What causes this failure is the presence of custom `install_command` inside default tox environment: https://github.com/openstack/tripleo-quickstart/blob/master/tox.ini#L10

**Comment by greg-hellings** [comment]
Hmm, what about this command is causing it to fail, though? Is it the presence of "-c" that prevents it from taking a list of deps? Is it that the molecule arguments are not present in the constraints? I'm not familiar with the use of a constraint file, personally, so I don't know how to address this.

**Comment by ssbarnea** [comment]
No idea, I was very busy today and was not able to debug it further. Still, is very strange as it does not always happens and when it does there are no logs left at all to indicate why it failed.

I would have expected an error caused by conflict in versions when same dependency is mentioned multiple times, but I do not have the proof yet.

**Comment by greg-hellings** [comment]
Is this still a problem?

**Comment by ssbarnea** [comment]
Closing because I left the team 9mo ago and if nobody complained, it must be working.
