### ISSUE TITLE
tox-ansible should also expose sanity/unit environments with other python versions

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox-ansible#91]
At this moment only `sanity` and `units` are added and they will only run with the same version of python that was used by tox itself.

This produces a problem, especially if your python is 3.9 because ansible-test does not run pylint on py3.9 due to ` Skipping sanity test 'pylint' on unsupported Python 3.9.`

That means that CI may report failures that you do not see locally unless you do something like `tox -e sanity -- --venv --python 3.8` to alter the python version used by sanity.

Ideally user should be able to run `tox -e sanity-py38` to do the same and tox should list this when running `tox -la`.

In fact I suspect it would be a good idea to detect all available python versions and assure that when running the short version, we include all of the available ones.

**Comment by greg-hellings** [comment]
If you want to run Ansible with specific versions of python, you can use the tag in the tox.ini file

```yaml
[ansible]
python = 3.8
```

That will apply to all generated environments discovered by the scenarios. If you want to use the same logic, we can apply it also to the `ansible-test` based environments. That will allow, also, a user to test across any set of Python versions they want by doing something like

```yaml
[ansible]
python = 2.7 3.5 3.8 3.10
```

**Comment by cidrblock** [comment]
Version 2 supports the full matrix of supported ansible and pytohn versions.

https://github.com/tox-dev/tox-ansible/blob/main/src/tox_ansible/plugin.py#L38
