### ISSUE TITLE
tox-ansible should not inherit deps or usedevelop from main testenv

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox-ansible#96]
While tox inherits all options from main `[testenv]` unless user overrides them, we do not want to do this for ansible environments as we will see them polluted too often.

We recently address the issue with `skipsdist` but `deps` and `usedevelop` also causes problems and potential conflicts.

**Comment by greg-hellings** [comment]
I definitely agree on the usedevelop. That needs to be specific for an Ansible requirement. But for deps, I'm not so sure. It's very possible to have modules (or to be using modules from Ansible) that require a particular package installed onto the runner. If that's not inherited from `{[testenv]deps}`, then where do we get it?

**Comment by cidrblock** [comment]
We now suggest an entirely seperate `tox-ansible.ini` file and warn if the user is not using one.  This should allow `tox-ansible` to be used where tox is already in place without contamination of the dynamically generated commands for ansible from the exisitng tox.ini testenv
